export const DWARF_LIST_REQUEST = 'DWARF_LIST_REQUEST'
export const DWARF_LIST_SUCCESS = 'DWARF_LIST_SUCCESS'
export const DWARF_LIST_FAIL = 'DWARF_LIST_FAIL'

export const DWARF_DETAILS_REQUEST = 'DWARF_DETAILS_REQUEST'
export const DWARF_DETAILS_SUCCESS = 'DWARF_DETAILS_SUCCESS'
export const DWARF_DETAILS_FAIL = 'DWARF_DETAILS_FAIL'
